Scripts for Service status update to HMI feature (Internal review)
dboltovskyi/sdl_atf_test_scripts pull request #12
Opened 2019-02-11 10:51 UTC by dboltovskyi

2019-02-12 14:49 UTC, GetmanetsIrina requested changes

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/001_Video_service_protected.lua
> +-- 1) send OnStatusUpdate(UP_TO_DATE) if Policy Table Update is successful
PTU is defined as successful in 
```
-- In case:
-- 2) Policy Table Update is Successful
```
so the condition `if Policy Table Update is successful` is redundant

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/002_Audio_service_protected.lua
> +-- 1) send StartSream() to HMI
StartSream() -> StartAudioStream()

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/005_Audio_service_unprotected.lua
> +-- 1) send StartSream() to HMI
StartSream() -> StartAudioStream()

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/006_RPC_service_unprotected.lua
> +-- 1) App is conected with NAVIGATION appHMIType
typo: conected

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/007_Protected_service_GetSystemTime_Rejected_INVALID_TIME.lua
> +-- 1) App is registered with NAVIGATION appHMIType and activated.
In precondition must be the info that Audio and Video services are force protected

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/007_Protected_service_GetSystemTime_Rejected_INVALID_TIME.lua
> +-- 2) send OnServiceUpdate (VIDEO, INVALID_TIME) to HMI
(VIDEO, INVALID_TIME) -> (**SERVICETYPE**, INVALID_TIME)
and in line 18

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/008_Unprotected_service_GetSystemTime_Rejected_INVALID_TIME.lua
> +-- 1) App is registered with NAVIGATION appHMIType and activated.
I propose to add info about the protection status( force protected and unprotected values in ini file ) to the precondition

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/009_Protected_service_GetSystemTime_invalid_response_INVALID_TIME.lua
> +-- 2) send OnServiceUpdate (VIDEO, REQUEST_RECEIVED) to HMI
(VIDEO, REQUEST_RECEIVED) -> (**SERVICETYPE**, REQUEST_RECEIVED)
The same in 10, 17,18

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/009_Protected_service_GetSystemTime_invalid_response_INVALID_TIME.lua
> +runner.Step("Start Audio Service protected with invalid response to request",
missed `GetSystemTime` -> `to GetSystemTime request`

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/010_Unprotected_service_GetSystemTime_invalid_response_INVALID_TIME.lua
> +-- 1) Mobile app requests StartService (Video encryption = true)
Missed comma after `Video`.
`Video` must be replaced with `SERVICETYPE` also in 13 line

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/011_Protected_service_GetSystemTime_no_response_INVALID_TIME.lua
> +-- 1) Mobile app requests StartService (Video encryption = true)
`Video, ` -> `SERVICETYPE,` also in 13,17,18.

Please perform the same update in 012 script.

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/015_RPC_service_protected_PTU_FAILED_TimeOut.lua
> +-- 1) send OnServiceUpdate (AUDIO, REQUEST_RECEIVED) to HMI
`AUDIO` -> `RPC`

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/018_RPC_service_protected_PTU_FAILED_invalid_data.lua
> +-- 1) send OnServiceUpdate (AUDIO, REQUEST_RECEIVED) to HMI
`AUDIO` -> `RPC`

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/019_Protected_service_mobile_INVALID_CERT.lua
> +-- 1) send OnStatusUpdate(UP_TO_DATE) if Policy Table Update is successful
Policy Table Update is successful according to 
```
-- In case:
-- 2) Policy Table Update is Successful
```
so `if Policy Table Update is successful` is redundant.

Please check through all scripts.

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/020_Unprotected_service_mobile_INVALID_CERT.lua
> +-- 2) send OnServiceUpdate (VIDEO, REQUEST_RECEIVED) to HMI
`VIDEO` -> `SERVICETYPE`

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/021_Protected_service_INVALID_CERT.lua
> +-- 1) Mobile app requests StartService (Video, encryption = true)
`VIDEO` -> SERVICETYPE, also in 13 line,
also please check in remained scripts and update.

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/024_Unprotected_service_sdl_cert_expire_in_24hr_INVALID_CERT.lua
> +-- force protected
Must be `not force protected and not force unprotected`

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/025_Protected_service_DecryptCertificate_rejected_INVALID_CERT_external.lua
> +-- 3) Determines that cert is invalid
Cert in DB is valid but HMI responds with error result code to DecryptCertificate_Rq, the same update is required in 026

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/027_Video_Audio_service_protected_several_apps.lua
> +-- 2) send OnServiceUpdate (SERVICETYPE, REQUEST_RECEIVED, AppID_2) to HMI
In case appdID id defined for app 2 so also must be defined in messages related to app 1

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/027_Video_Audio_service_protected_several_apps.lua
> +-- 6) send StartServiceACK (ServiceType, encryption = true) to mobile app_2
Please update all `ServiceType` to `SERVICETYPE`

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/027_Video_Audio_service_protected_several_apps.lua
> +-- In case:
```
-- In case:
-- 3) App_2 activated and requests StartService (Video, encryption = true)
```

2019-02-12 14:49 UTC, GetmanetsIrina commented on test_scripts/API/ServiceStatusUpdateToHMI/common.lua
> +function m.preconditions(pForceProtectedServices, pForceUnprotectedServices)
The are no cases where `pForceUnprotectedServices` is set, so `pForceUnprotectedServices` parameter can be removed and set `ForceUnprotectedService` always to `Non`

2019-02-13 11:00 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/001_Video_service_protected.lua
> +-- 1) send OnStatusUpdate(UP_TO_DATE) if Policy Table Update is successful
corrected

2019-02-13 11:02 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/002_Audio_service_protected.lua
> +-- 1) send StartSream() to HMI
corrected

2019-02-13 11:05 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/005_Audio_service_unprotected.lua
> +-- 1) send StartSream() to HMI
corrected

2019-02-13 11:06 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/006_RPC_service_unprotected.lua
> +-- 1) App is conected with NAVIGATION appHMIType
corrected

2019-02-13 11:12 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/007_Protected_service_GetSystemTime_Rejected_INVALID_TIME.lua
> +-- 1) App is registered with NAVIGATION appHMIType and activated.
corrected

2019-02-13 11:14 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/007_Protected_service_GetSystemTime_Rejected_INVALID_TIME.lua
> +-- 2) send OnServiceUpdate (VIDEO, INVALID_TIME) to HMI
corrected

2019-02-13 11:48 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/008_Unprotected_service_GetSystemTime_Rejected_INVALID_TIME.lua
> +-- 1) App is registered with NAVIGATION appHMIType and activated.
corrected

2019-02-13 11:51 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/009_Protected_service_GetSystemTime_invalid_response_INVALID_TIME.lua
> +-- 2) send OnServiceUpdate (VIDEO, REQUEST_RECEIVED) to HMI
corrected

2019-02-13 11:52 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/009_Protected_service_GetSystemTime_invalid_response_INVALID_TIME.lua
> +runner.Step("Start Audio Service protected with invalid response to request",
corrected

2019-02-13 11:55 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/010_Unprotected_service_GetSystemTime_invalid_response_INVALID_TIME.lua
> +-- 1) Mobile app requests StartService (Video encryption = true)
corrected

2019-02-13 11:56 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/011_Protected_service_GetSystemTime_no_response_INVALID_TIME.lua
> +-- 1) Mobile app requests StartService (Video encryption = true)
corrected

2019-02-13 11:57 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/015_RPC_service_protected_PTU_FAILED_TimeOut.lua
> +-- 1) send OnServiceUpdate (AUDIO, REQUEST_RECEIVED) to HMI
corrected

2019-02-13 11:57 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/018_RPC_service_protected_PTU_FAILED_invalid_data.lua
> +-- 1) send OnServiceUpdate (AUDIO, REQUEST_RECEIVED) to HMI
corrected

2019-02-13 11:58 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/019_Protected_service_mobile_INVALID_CERT.lua
> +-- 1) send OnStatusUpdate(UP_TO_DATE) if Policy Table Update is successful
corrected

2019-02-13 11:59 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/020_Unprotected_service_mobile_INVALID_CERT.lua
> +-- 2) send OnServiceUpdate (VIDEO, REQUEST_RECEIVED) to HMI
corrected

2019-02-13 12:00 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/021_Protected_service_INVALID_CERT.lua
> +-- 1) Mobile app requests StartService (Video, encryption = true)
corrected

2019-02-13 12:04 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/024_Unprotected_service_sdl_cert_expire_in_24hr_INVALID_CERT.lua
> +-- force protected
corrected

2019-02-13 12:07 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/025_Protected_service_DecryptCertificate_rejected_INVALID_CERT_external.lua
> +-- 3) Determines that cert is invalid
corrected

2019-02-13 12:20 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/027_Video_Audio_service_protected_several_apps.lua
> +-- 6) send StartServiceACK (ServiceType, encryption = true) to mobile app_2
corrected

2019-02-13 12:21 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/027_Video_Audio_service_protected_several_apps.lua
> +-- In case:
corrected

2019-02-13 12:24 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/027_Video_Audio_service_protected_several_apps.lua
> +-- 2) send OnServiceUpdate (SERVICETYPE, REQUEST_RECEIVED, AppID_2) to HMI
corrected

2019-02-13 12:30 UTC, amakarinskii commented on test_scripts/API/ServiceStatusUpdateToHMI/common.lua
> +function m.preconditions(pForceProtectedServices, pForceUnprotectedServices)
corrected

2019-02-13 15:32 UTC, merged